language: php

php:
  - 5.5
  - 5.6
  - hhvm

script:
 - composer install
 - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
